config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("hello/", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tinkerhub_tinkercade.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("api/auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path("", include("tinkerhub_tinkercade.games.urls", namespace="games")),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tinkerhub_tinkercade/games/urls.py
from django.urls import path
from tinkerhub_tinkercade.games.views import (
    gamees_list_view,
    single_game_view,
    user_list_view,
    user_rank_view,
    game_list,
    game_detail,

)

app_name = "games"

urlpatterns = [
    path("all/<str:level>", view=gamees_list_view, name="games_list"),
    path("get-user-list/", view=user_list_view, name="user-list"),
    path("get/<slug:slug>/", view=single_game_view, name="single-game"),
    path('leaderboard/', view=user_rank_view, name='user-rank'),
    path('', game_list, name='game_list'),
    path('game/<slug:slug>/', game_detail, name='game_detail'),

    
]

tinkerhub_tinkercade/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view, google_login

app_name = "users"
urlpatterns = [
    path("google/", view=google_login, name="google"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),

]

tinkerhub_tinkercade/games/models.py
from django.db import models

from tinkerhub_tinkercade.users.models import User
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify

class Games(models.Model):
    name = models.CharField(max_length=14, unique=True)
    desc = models.CharField(max_length=200)
    points = models.IntegerField(default=10, null=True, blank=True)
    slug = models.SlugField(max_length=50, unique=True, editable=False)
    class Levels(models.TextChoices):
        LEVEL1 = "L1", _("Level-1")
        LEVEL2 = "L2", _("Level-2")
        LEVEL3 = "L3", _("Level-3")
    level = models.CharField(max_length=3, choices=Levels.choices,default=Levels.LEVEL1)
    quiz_link = models.URLField(max_length=500, null=True, blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name).upper()
        
        return super(Games, self).save(*args, **kwargs)


class UserGames(models.Model):
    id = models.CharField(max_length=100, default="TINKERCADE", primary_key=True)
    player = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name="player"
    )
    games = models.ForeignKey(Games, on_delete=models.CASCADE)
    winning_points = models.IntegerField(default=0, null=True, blank=True)
    
    def __str__(self):
        return self.id

    @staticmethod
    def create_random_id():
        return random.randrange(1000, 9999)

    def save(self, *args, **kwargs):
        if not self.id:
            temp_id = f"TINKERCADE-{self.game.name.split()[0]}-{UserGames.create_random_id()}"
            while UserGames.objects.filter(id=temp_id).first():
                temp_id = (
                    f"TINKERCADE-{self.game.name.split()[0]}-{UserGames.create_random_id()}"
                )
            # self.slug = temp_id.upper()
            self.id = temp_id.upper()
        return super(UserGames, self).save(*args, **kwargs)
    

tinkerhub_tinkercade/users/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db.models import CharField, BooleanField, TextChoices, URLField, IntegerField

class User(AbstractUser):
    """
    Default custom user model for tinkerhub_tinkercade.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore[assignment]
    last_name = None  # type: ignore[assignment]
    profile_image = URLField(max_length=3000, null=True, blank=True)
    points = IntegerField(default=30, null=True, blank=True)

    class UserType(TextChoices):
        PARTICIPANTS = "P", _("Participants")
        CORDS = "C", _("Coordinator")
        VOLUNTEER = "V", _("Volunteer")
        ADMIN = "A", _("Admin")

    user_type = CharField(
        max_length=1,
        choices=UserType.choices,
        default=UserType.PARTICIPANTS,
    )
    phone = IntegerField(default=0)
    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})
    def __str__(self):
        return self.email
    class Meta:
        ordering = ["-email"]

tinkerhub_tinkercade/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].required = False  # Make password1 field not required
        self.fields['password2'].required = False 

    def save(self, commit=True):
        # Override save method to create user without setting passwords
        user = super().save(commit=False)
        user.set_unusable_password()  # Set unusable password
        if commit:
            user.save()
        return user

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

tinkerhub_tinkercade/games/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework.generics import (
    # CreateAPIView,
    ListAPIView,
    RetrieveAPIView,
    # UpdateAPIView,
    # ListCreateAPIView,
    # get_object_or_404,
)

from tinkerhub_tinkercade.games.serializers import (
    GamesSerializer
)
from tinkerhub_tinkercade.users.api.serializers import (
    UserSerializer
)
from tinkerhub_tinkercade.games.models import Games
from tinkerhub_tinkercade.users.models import User
from django.views.generic import TemplateView



# Create your views here.
class GamesListView(ListAPIView):
    serializer_class = GamesSerializer
    queryset = Games.objects.all()

    def get_queryset(self):
        level = self.kwargs.get('level')
        queryset = Games.objects.filter(level=level)
        return queryset

    class Meta:
        model = Games
        fields = "__all__"

gamees_list_view = GamesListView.as_view()

class SingleGameView(RetrieveAPIView):
    queryset = Games.objects.all()
    lookup_field = "slug"
    serializer_class = GamesSerializer

    class Meta:
        model = Games
        fields = "__all__"

single_game_view = SingleGameView.as_view()

class UsersListView(ListAPIView):
    serializer_class = UserSerializer
    def get_queryset(self):
        queryset = User.objects.order_by("points")
        return queryset
user_list_view = UsersListView.as_view()

 # Assuming you have a User model

class UserRankView(TemplateView):
    template_name = 'user_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.order_by('-points')  # Retrieve users sorted by points
        context['users'] = users
        return context
user_rank_view = UserRankView.as_view()

def user_list(request):
    users=User.objects.order_by("-points")
    return render(request, 'user_list.html', {'users': users})

def game_list(request):
    games = Games.objects.order_by("level")
    resp = render(request, 'game_list.html', {'games': games})
    resp["ngrok-skip-browser-warning"]=False
    return resp

def game_detail(request, slug):
    game = Games.objects.get(slug=slug)
    return render(request, 'game_detail.html', {'game': game})

tinkerhub_tinkercade/users/api/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin
from rest_framework.mixins import RetrieveModelMixin
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth import get_user_model

from .serializers import UserSerializer

User = get_user_model()

class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        user = request.user
        if user.is_authenticated:
            try:
                data = SocialAccount.objects.get(
                    provider="google", user=user
                ).extra_data
                picture = data.get("picture")
                user.profile_image = picture
                if not user.name:
                    user.name = user.username
                user.save()

            except SocialAccount.DoesNotExist:
                pass
            except KeyError:
                pass
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

tinkerhub_tinkercade/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from tinkerhub_tinkercade.users.models import User
from allauth.socialaccount.models import SocialAccount
from dj_rest_auth.registration.serializers import SocialLoginSerializer
from dj_rest_auth.registration.views import SocialLoginView
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()
class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

class GoogleLogin(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client
    callback_url = (
        "https://tinkercade.hestiatkmce.in/"
        if not settings.DEBUG
        else "https://127.0.0.1:8000/"
    )
    callback_url += "accounts/google/login/callback/"
    serializer_class = SocialLoginSerializer

    def get_serializer(self, *args, **kwargs):
        serializer_class = self.get_serializer_class()
        kwargs["context"] = self.get_serializer_context()
        return serializer_class(*args, **kwargs)

google_login = GoogleLogin.as_view()

tinkerhub_tinkercade/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

tinkerhub_tinkercade/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
      tinkerhub_tinkercade
    {% endblock title %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description"
        content="tinkerhub_tinkercade" />
  <meta name="author"
        content="Namritha C" />
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
          integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
<!-- Your stuff: Third-party CSS libraries go here -->
<!-- This file stores project-specific CSS -->

  
  <link href="{% static 'css/project.css' %}" rel="stylesheet" />


{% endblock css %}
<!-- Le javascript
    ================================================== -->
{# Placed at the top of the document so pages load faster with defer #}
{% block javascript %}


<!-- Bootstrap JS -->
<script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
<!-- Your stuff: Third-party javascript libraries go here -->


<!-- place project specific Javascript in this file -->

  
  <script defer src="{% static 'js/project.js' %}"></script>


{% endblock javascript %}
</head>
<body class="{% block bodyclass %}{% endblock bodyclass %}">
  {% block body %}
  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler navbar-toggler-right"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">tinkerhub_tinkercade</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link"
                   href="{% url 'users:detail' request.user.username %}">{% translate "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
              </li>
            {% else %}
              {% if ACCOUNT_ALLOW_REGISTRATION %}
                <li class="nav-item">
                  {# URL provided by django-allauth/account/urls.py #}
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}
    {% block main %}
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    {% endblock main %}

  </div>
  {% endblock body %}
  <!-- /container -->
  {% block modal %}
  {% endblock modal %}
  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
  {% endblock inline_javascript %}
</body>
</html>

tinkerhub_tinkercade/templates/game_detail.html
<!-- game_detail.html -->
{% extends 'main_page.html' %}

{% block content %}
<style>
    /* Your CSS styles */
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #fff; /* White background color */
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
        text-align: center;
        color: #333; /* Dark gray text color */
    }
    p {
        color: #666; /* Medium gray text color */
    }
    .quiz-link {
        text-align: center;
        margin-top: 20px;
    }
    .quiz-link a {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff; /* Blue background color */
        color: #fff; /* White text color */
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s;
    }
    .quiz-link a:hover {
        background-color: #0056b3; /* Darker blue color on hover */
    }
</style>

<div class="container">
    <h1>{{ game.name }}</h1>
    <div class="quiz-link">
        <a href="{{ game.quiz_link }}">Take the techQuiz</a>
    </div>
    <!-- Add more details here as needed -->
</div>
{% endblock %}

tinkerhub_tinkercade/templates/game_list.html
<!-- templates/game_list.html -->
{% extends 'main_page.html' %}

{% block content %}
<style>
    /* Custom CSS styles for game list page */
    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f0f0f0; /* Light gray background color */
        border-radius: 10px;
    }
    h1 {
        text-align: center;
        color: #333; /* Dark gray text color */
    }
    .game-item {
        background-color: #fff; /* White background color */
        border: 1px solid #ddd; /* Light gray border */
        border-radius: 5px;
        padding: 20px;
        margin-bottom: 20px;
    }
    .game-info {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
    }
    .level {
        font-size: 1.2em; /* Larger font size */
        font-weight: bold;
        color: #333; /* Dark gray text color */
    }
    .game-name {
        font-size: 1.2em; /* Larger font size */
        font-weight: bold;
        color: #007bff; /* Blue text color */
        font-family: 'Arial', sans-serif; /* Beautiful font for game name */
    }
    .points {
        font-size: 1.2em; /* Larger font size */
        font-weight: bold;
        color: #28a745; /* Green text color */
    }
</style>

<div class="container">
    <h1>Games @ Arcade</h1>
    {% for game in games %}
    <div class="game-item">
        <div class="game-info">
            <div class="level">Level: {{ game.level }}</div>
            <div class="game-name">
                <a href="{% url 'games:game_detail' game.slug %}">{{ game.name }}</a>
            </div>
            <div class="points">Points : {{ game.points }}</div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

tinkerhub_tinkercade/templates/main_page.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TinkerCade : The Tech ARCADE{% endblock %}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #ffe600; /* Bright yellow background color */
            font-family: Arial, sans-serif;
            color: #fff;
        }
        header {
            background-color: #4b2b00; /* Light brown header color */
            padding: 20px 0;
            text-align: center;
        }
        header h1 {
            color: #fff; /* Title color */
        }
        .options {
            display: flex;
            justify-content: space-around;
        }
        .option {
            padding: 15px 30px; /* Increased padding for larger options */
            background-color: rgba(234, 231, 231, 0.5);
            border-radius: 5px;
            text-decoration: none;
            color: #fff;
            transition: background-color 0.3s;
            font-size: 18px; /* Increased font size */
        }
        .option:hover {
            background-color: rgba(255, 255, 255, 0.2);
        }
    </style>
</head>
<body>
    <header>
        <h1>TinkerCade : The Tech ARCADE</h1>
        <div class="options">
            <a href="{% url 'games:user-rank' %}" class="option">Leaderboard</a>
            <a href="{% url 'games:game_list' %}" class="option">Games List</a>
        </div>
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

tinkerhub_tinkercade/templates/user_list.html
<!-- user_list.html -->
{% extends 'main_page.html' %}

{% block content %}
<style>
    /* Your CSS styles */
    h1{
        color: #333;
        align-self: center;
    }
    .user-list {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f8f9fa; /* Light gray background color */
    }
    .user-box {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
        padding: 15px;
        background-color: #fff; /* White background color */
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .user-box:hover {
        background-color: #f0f0f0; /* Light gray background color on hover */
    }
    .username {
        font-weight: bold;
        color: #333; /* Dark gray text color */
    }
    .user-points {
        color: #28a745; /* Green text color for points */
    }
</style>

<div class="user-list">
    <h1>Leaderboard</h1>
    {% for user in users %}
        <div class="user-box">
            <span class="username">{{ user.username }}</span>
            <span class="user-points">{{ user.points }}</span>
        </div>
    {% endfor %}
</div>
{% endblock %}